### ISSUE TITLE
Docs : broken "nodes" page

### ISSUE THREAD

**Issue by GTorreil** [kayjan/bigtree#270]
**Describe the issue**
The [nodes page](https://bigtree.readthedocs.io/en/stable/home/bigtree/node/index.md), as opened by clicking "Nodes" on [this page](https://bigtree.readthedocs.io/en/stable/home/tree/#node), is seemingly broken. 

**Environment**
Does not apply / Web

**To Reproduce**
Steps or code to reproduce the behaviour:
1. Go to [this documentation page](https://bigtree.readthedocs.io/en/stable/home/bigtree/node/index.md)
2. Click on the "nodes" title
3. [the page](https://bigtree.readthedocs.io/en/stable/home/tree/#node), is seemingly broken. 

**Expected behaviour**
Readable layout

**Screenshots**
![image](https://github.com/kayjan/bigtree/assets/16188760/3657b42b-acfe-42d7-ba3c-4a255cd81628)

**Comment by kayjan** [comment]
Thanks for spotting this! Let me fix it

**Comment by kayjan** [comment]
It is fixed now on [this](https://bigtree.readthedocs.io/en/stable/home/tree/#node) page

**Comment by GTorreil** [comment]
I can confirm that. Thanks for this great project !

**Comment by GTorreil** [comment]
Hello, if you don't mind me reopening, this exact issue just occured to me [on this plage](https://bigtree.readthedocs.io/en/latest/bigtree/tree/construct.html).
