### ISSUE TITLE
Mermaid Chart Customization Bug

### ISSUE THREAD

**Issue by akrammiriyev** [kayjan/bigtree#273]
**Describe the issue**
I am new user of bigtree and while building tree for mermaid markdown I noticed nodes are not colored as specified in node_style. 
Then I checked original documentation in the following link: https://bigtree.readthedocs.io/en/stable/bigtree/tree/export/#bigtree.tree.export.tree_to_mermaid
![image](https://github.com/user-attachments/assets/0a16c964-6189-4a23-8e4f-ab58cec51aa0)

Example markdown also not generating expected result. In code it is written to color node "d" in yellow. Mermaid markdown file generated in such a way that node "b" colored in yellow. See mermaid result here : https://mermaid.live/edit#pako:eNpNkV1vgyAUhv8KOYlxS9SAtX6QtBdbb3e1XS3cUMVKitIgruus_33UfqTh5uXl4T2HwwilrgRQ8LwRyU5aikbk10ofy4Yb68_bcjA_wkl_y3vZ-2i6LM9j3YNDX2-swyMDzmBCq9X6_N5IVSFyRjjELwy2DF4dEWJKaal43zsZYhSGazQrh1R35OES54qre48Oo_CeHV-yL0g5I3PqRtSoEjUflEW9NXovwqOsbEPJE_BUv5ZK0ZNQ7h3B7QLdKl7uIYBWmJbLys1mZB1CDGwjWtcOdfJWgwHrJofywerPU1cCtWYQARg97BqgNVe92w2HiluxkXxnePtwRSWtNh_X6c-fEMCBd0BH-AWaJdGyKBJC4mWckkUSwAkoKYqIFHG2iIskTwnOpwD-tHaZOMpwmuUFztJFnMdZls5h3_PhpafpH_Y7lIw 

with my limited python knowledge I understand it has something to do with mermaid class name addition in export.py file, but I am unable to solve it.

**Environment**
Describe your environment.
 - Platform: [Windows]
 - Python version:3.12.4
 - `bigtree`  version:0.19.13

**Comment by kayjan** [comment]
Good catch. Will fix this, thanks for raising the issue!

**Comment by kayjan** [comment]
This is fixed in v0.19.4, have updated the documentation as well. Closing this issue!
