### ISSUE TITLE
different separator in subtree

### ISSUE THREAD

**Issue by fostermaier** [kayjan/bigtree#303]
### Describe the issue

When taking a subtree, the separator of the subtree is different from the separator of the original tree.
This feels like a very unexpected behavior.

### Environment

- Platform: Windows
- Python version: 3.12
- `bigtree` version: 0.19.3

### To Reproduce

    from bigtree import Node, get_subtree
    
    tree = Node("a", sep='.')
    b = Node("b", parent=tree)
    c = Node("c", parent=b)
    d = Node("d", parent=b)
    e = Node("e", parent=tree)
    print(tree.path_name)

    >> .a

    
    subtree = get_subtree(tree, '.a.b')
    print(subtree.path_name)

    >> /b

### Expected behaviour

check `sep` of original root node and propagate to root node of subtree accordingly

### Final Check

- [X] I will watch this issue to stay updated with any comments or requests for additional information. I understand that timely responses will help in resolving the issue more quickly.

- [X] I have thoroughly searched the documentation, and I have also checked for existing solutions or similar issues before submitting this issue.

**Comment by fostermaier** [comment]
exemplary fix:
patch `get_subtree` to assign original `sep` to new root node before returning

    subtree = get_subtree(tree, '.a.b')
    subtree.sep = tree.sep
    print(subtree.path_name)

    >> .b

**Comment by kayjan** [comment]
Hello, thanks for noticing this! `sep` was purposely set to only modify the root sep so the sep is supposed to "propagate" to every descendant node instead of changing every single node's sep, hence inevitably leading to discrepancy which is expected. But I did not consider this for `get_subtree`, good catch :) Will fix it
