### ISSUE TITLE
Attribute values

### ISSUE THREAD

**Issue by virsto** [kayjan/bigtree#33]
You have some nice examples for defining a tree structure in your code. However, your code does not allow certain attribute values. The examples in your code use age where ages can be positive are negative(?) but do not allow a value of 0 -- Why? Suppose I wished to have an attribute at each node that represents the number of bytes for each node, e.g. Node("c",bytes=0,parent=root). When a node has 0 bytes your code will display the name of the node but not the value of 0. And why are integer values of ages converted to float values?

In general, I am very impressed by your bigtree package -- I use it quite often for zipping complex directories and encryption/decryption.  Keep up the good work :-)

**Comment by kayjan** [comment]
There isn't any restrictions on the attribute values or data type conversions - can you provide examples where you cannot set the age attribute as 0 and when the integer value attributes get converted to float values?

For the conditional printing (i.e., print node name if byte=0, else display the byte value), you can use `yield_tree` for this. For example,

```python
from bigtree import Node, yield_tree

# Construct tree
root = Node("a", byte=1)
b = Node("b", byte=0, parent=root)
c = Node("c", byte=1, parent=root)
d = Node("d", byte=-1, parent=b)

# Conditional printing
for branch, stem, node in yield_tree(root):
    if node.byte:
        print(f"{branch}{stem}{node.node_name} [byte={node.byte}]")
    else:
        print(f"{branch}{stem}{node.node_name}")
```
This will result in the output
```
a [byte=1]
├── c [byte=1]
└── b
    └── d [byte=-1]
```
Hope this helps!
