### ISSUE TITLE
Are BTrees and Binary Trees the same?

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [kayjan/bigtree#34]
Quote from README

```
There are 3 segments to Big Tree consisting of Tree, Binary Tree (BTree), and Directed Acyclic Graph (DAG) implementation.
```

Though used in this context as an abbreviation, i think a BTree is not a binary tree

**Comment by kayjan** [comment]
Thanks for pointing this out! I have made the correction in v0.6.7
