### ISSUE TITLE
Typed package

### ISSUE THREAD

**Issue by jzazo** [kayjan/bigtree#46]
Hi! I am starting to explore the library. One thing I noticed is that some parts are typed (not sure if everything). Do you mind declaring that your package is typed if it is? You need to add a `py.typed` file at the root of the source. [Link1](https://peps.python.org/pep-0561/#packaging-type-information) and [link2](https://mypy.readthedocs.io/en/stable/installed_packages.html#making-pep-561-compatible-packages).

**Comment by kayjan** [comment]
Hi, have added type checking with mypy. Thanks for your suggestion!
