### ISSUE TITLE
How to build a html tree

### ISSUE THREAD

**Issue by jet10000** [kayjan/bigtree#74]
How to build "ul li" or "table" html tree ?

**Comment by jet10000** [comment]
Thanks, is it possible to convert the `<ul>` and `li` back to bigtree?

**Comment by kayjan** [comment]
It is a little tricky to read in the HTML raw code, but you can display the HTML structure and use `str_to_tree` similar to [this](https://github.com/kayjan/bigtree/issues/75) issue.

**Comment by jet10000** [comment]
I temporarily use `html2markdown` to convert html tree into markdown tree, and then into bigtree. 

Expect to have a built-in method in the future.

**Comment by kayjan** [comment]
Do open a new issue and describe your use case and provide sample input if possible.

However, there are a lot of HTML tags and not all of the tags are related to tree hierarchical structure. If your workaround works, to make use of `html2markdown`, then duplicated efforts would be redundant in `bigtree`.
