### ISSUE TITLE
Convert markdown list into bigtree

### ISSUE THREAD

**Issue by jet10000** [kayjan/bigtree#75]
```
* abc
  * 123
  * 456(name='test', age=10)
* efg
* opq
* rst
```
convert markdown to bigtree

**Comment by Abdur-rahmaanJ** [comment]
@jet10000 Do you have a use case for this?

**Comment by kayjan** [comment]
Hi, thanks for using `bigtree`, this function from markdown/text to tree it already available in `str_to_tree` method. However, it only converts the tree structure and will not be able to infer the node attributes (in your case, the name and age attributes) as the whole string will be interpreted as a node name.

Another tweak I made was that the resulting tree needs to have a distinct root node, meaning that `abc`, `efg`, `opq`, etc. should all have a common parent.

```python
tree_str = """
root
* abc
  * 123
  * 456(name='test', age=10)
* efg
* opq
* rst
"""

from bigtree import str_to_tree
tree = str_to_tree(tree_str, tree_prefix_list=["\* "])  # added \ as it is interpreted as regex

tree.show()
```

This will result in output,

```
root
├── abc
│   ├── 123
│   └── 456(name='test', age=10)
├── efg
├── opq
└── rst
```

**Comment by jet10000** [comment]
> @jet10000 Do you have a use case for this?

Organizing and convert book catalogs and then save it to the database, Many book catalogs are written by markdown or text.

```
* chapter1(page_no=1)
  * node1(page_no=2)
  * node2(page_no=20)
* chaper2(page_no=21)
  * node3(page_no=22)
```

**Comment by jet10000** [comment]
How to convert markdown 

> Hi, thanks for using `bigtree`, this function from markdown/text to tree it already available in `str_to_tree` method. However, it only converts the tree structure and will not be able to infer the node attributes (in your case, the name and age attributes) as the whole string will be interpreted as a node name.
> 
> Another tweak I made was that the resulting tree needs to have a distinct root node, meaning that `abc`, `efg`, `opq`, etc. should all have a common parent.
> 
> tree_str = """
> root
> * abc
>   * 123
>   * 456(name='test', age=10)
> * efg
> * opq
> * rst
> """
> 
> from bigtree import str_to_tree
> tree = str_to_tree(tree_str, tree_prefix_list=["\* "])  # added \ as it is interpreted as regex
> 
> tree.show()
> This will result in output,
> 
> ```
> root
> ├── abc
> │   ├── 123
> │   └── 456(name='test', age=10)
> ├── efg
> ├── opq
> └── rst
> ```

https://preline.co/docs/tree-view.html

How to convert markdown to preline tree-view? Thanks

**Comment by kayjan** [comment]
The preline website shows tree in HTML code, do you want to create tree from markdown or HTML? If you want to "convert markdown to preline tree-view", why would you need bigtree?

It is recommended to create a new issue for this, because issue creation enforces a template for you to fill in what is the issue / what you want to achieve that would help me understand better. Thanks!
