### ISSUE TITLE
Bigtree without pandas

### ISSUE THREAD

**Issue by zink-chimaera** [kayjan/bigtree#78]
Is there a way to use bigtree without pandas now in the future?

This would help users that:
* try to keep their dependencies to a minimum, or
* Are switching away from pandas (e.g. to polars)

This could be done by hiding the pandas behind a feature flag or to have it as an optional import.

**Comment by kayjan** [comment]
Making pandas an optional library has been raised as an issue previously, you can refer to the [issue](https://github.com/kayjan/bigtree/issues/47) .

**Comment by phil65** [comment]
Is this on the roadmap? The other issue doesnt give a clear answer.

**Comment by zink-chimaera** [comment]
As far as I've seen @kayjan doesn't intend to.

I've hotfixed this for our use case but if you don't want to have pandas (e.g. because pyinstaller doesn't work with pandas) you need to switch to `anytree` (https://github.com/c0fec0de/anytree/)

**Comment by kayjan** [comment]
@phil65 

One of the main features of bigtree is the integration with Python lists, dictionaries, and pandas DataFrames. Under the hood, the methods are dependent on each other, for example creating tree from dictionary (dict_to_tree) converts it to pandas Dataframe and performs dataframe_to_tree. You can view the dependency graph [here](https://bigtree.readthedocs.io/en/latest/bigtree/tree/construct.html). Given the interdependency between methods and the popularity of pandas, I would prefer to leave it as a required library.

**Comment by phil65** [comment]
It´s fine, I´m just extracting the stuff I need then.  But I´m sure having such a super heavy dependency will prohibit a lot of developers from using this package directly (as you can see from the requests popping up). I love pandas, but pandas is HEAVY, and there should be a good reason to depend on it (which I dont see here).
Anyways, thank you for your efforts. It´s a nice library.

**Comment by kayjan** [comment]
**Update**: Pandas is now an optional library in `v0.12.0`!

Thanks for all your support and suggestions in making `bigtree` better 😄
