### ISSUE TITLE
Mermaid flowchart feature

### ISSUE THREAD

**Issue by liewshin** [kayjan/bigtree#97]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to be able to export trees into mermaid flowcharts such as
```mermaid
flowchart TD
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fa:fa-car Car]
```

Documentation: http://mermaid.js.org/syntax/flowchart.html

**Describe alternatives you've considered**
There is no alternative other than manually creating the mermaid flowcharts.

**Additional context**
NA

**Comment by kayjan** [comment]
Hi, thanks for raising this issue! The fix is implemented in v0.13.0, do upgrade bigtree with the command `pip install --upgrade bigtree`.
